FROM debian:stable-slim

ENV PYTHONUNBUFFERED=1 DOCKER=1 DEBIAN_FRONTEND=noninteractive

# Add support for apt-* packages caching through "apt-cacher-ng"
ARG APTPROXY
RUN bash -c 'if [ -n "$APTPROXY" ]; then echo "Acquire::HTTP::Proxy \"http://$APTPROXY\";" > /etc/apt/apt.conf.d/01proxy; fi'

## Install dependencies
RUN apt-get update \
    && apt-get --no-install-recommends install -y wget apt-utils vim-tiny \

    # Python system packages
    python3 python3-pip python3-dev \
    # PIP build dependencies
    gcc libssl-dev \

    && pip3 install -U pip 3to2 \

    # Backup dependencies
    && wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | apt-key add - \
    && echo "deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main" >> /etc/apt/sources.list.d/pgdg.list \
    && mkdir -p /usr/share/man/man1/ /usr/share/man/man7/ \
    && apt-get update && apt-get install -y postgresql-client-9.6 cron \

    # Cleanup after installation
    && apt-get clean -y \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && rm -fr /var/lib/apt/lists/* \

    # Create basic project structure
    && mkdir -p /code/

WORKDIR /code

ADD requirements.txt requirements.txt
RUN pip3 install -r requirements.txt --no-cache-dir

# Backup database every day
RUN (crontab -l 2>/dev/null; echo "00 04 * * * /code/manage.py dbbackup -z") | crontab - \
    && cron

EXPOSE 8000
