version: '2'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: 'project'
      POSTGRES_PASSWORD: ''

  cache:
    image: redis

  assets:
    build:
      dockerfile: docker/development/Dockerfile.assets
      context: .
    volumes:
      - ./project/assets:/app/project/assets/
    command: npm run watch

  manage:
    build:
      context: .
      dockerfile: docker/development/Dockerfile.web
    volumes:
      - ./:/code/

  web:
    extends:
      service: manage
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - db
      - cache
      - assets
